### PR TITLE
Bugfix: time stamps in clickstream zeros get not displayed

### PR DESCRIPTION
**Pull request by Maaiins**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tested the changes
- [ ] Build (`/path/to/php cli.php cmd=build`) was run locally and any changes were pushed

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: #545 

## What is the new behavior?
If there are less than two digits in hour, minute or second leading zeros gets displayed now

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Docs need to be updated?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by padams** [comment]
Hmm. Perhaps we should use makes new template function for this that takes a timestamp. That way we can localize the time/date format via a setting.

**Comment by Maaiins** [comment]
I searched through the repo, this is the only place where a timestamp is displayed this way. I think we simply should move to the session timestamp as elsewhere instead of displaying each separated.

**Comment by padams** [comment]
Yes! Although its the request timestamp no?

**Comment by Maaiins** [comment]
Yeah correct it´s the request timestamp, but anyway the field is called the same :-D

**Pull request merged**
