### PR TITLE
Feature - allow document updating

### PR DESCRIPTION
**Pull request by krytenuk**
**### Feature**
Added the updating of the page title and type to an existing document when the tracer request is processed. This is activated by a new config constant.

### CODE REVIEW

**Comment by padams** [comment]
You have the right idea but there is already a generic config setting for this called `allow_slowly_changing_dimensions`.

See how the referer event handler uses it.

**Comment by garryxigen** [comment]
Thanks @padams , I have removed the constant in favor of the `allow_slowly_changing_dimensions` setting you pointed out above. 
This however will cause the page title and type updates by default, this setting is true in the repository thus changing the current default behavior of not updating them.

**Comment by padams** [comment]
True, the best way to do this might be to have the handler code check the allow_slowly_changing dimensions flag AND see if the name of the entity that needs updating is in a new config array called something like `slowly_changing_dimension_entities`.

**Comment by padams** [comment]
Looks good.

**Pull request merged**
