### PR TITLE
Criterion9 php8 dynamic attributes and other similar php version change issues

### PR DESCRIPTION
**Pull request by criterion9**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tested the changes
- [ ] Build (`/path/to/php cli.php cmd=build`) was run locally and any changes were pushed

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Other (please describe): 
PHP8 related errors due to changes in PHP (attributes must be declared before being set, optional parameters cannot come before required parameters, and extended class method declarations must be compatible with the parent class)

## What is the current behavior?
PHP8.0|1.x produces errors related to changes in the syntax strictness of PHP.

Issue Number: 893

## What is the new behavior?

Less errors are produced for PHP8.0|1.x environments.
-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Docs need to be updated?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by mbtools** [comment]
I have done similar changes. Thanks for bringing this solution up-to-par with PHP releases. Not sure if this handles everything for PHP 8.3 yet but it's certainly going in the right direction 👍

**Comment by criterion9** [comment]
> I have done similar changes. Thanks for bringing this solution up-to-par with PHP releases. Not sure if this handles everything for PHP 8.3 yet but it's certainly going in the right direction 👍

Thanks! I have a handful to update the php SDK also for php 8.x

**Comment by mbtools** [comment]
I really, really want to get OWA to work well for all my WordPress sites so I'm updating / testing the WP plugin, too. 

But we need Peter to help and merge too @padams  🙏

**Review by padams — APPROVED** [review]
These look good.

**Comment by BloodyIron** [comment]
Are we going to get a new release version @padams with PHPv8.x support? The last release was January 7 2023.

**Comment by BloodyIron** [comment]
So what's going on here with PHP8.x and OWA? 8 months since the last commit and radio silence for this and seemingly plenty other topics.

This tool _NEEDS_ to have PHP version support significantly increased as the currently max version of PHP it can work with has been EOL for a long time. This is causing lots of problems and it would benefit many to know what's going on, including threads like #893 and more.

**Comment by criterion9** [comment]
> So what's going on here with PHP8.x and OWA? 8 months since the last commit and radio silence for this and seemingly plenty other topics.
> 
> This tool _NEEDS_ to have PHP version support significantly increased as the currently max version of PHP it can work with has been EOL for a long time. This is causing lots of problems and it would benefit many to know what's going on, including threads like #893 and more.

We've been running with PHP8 in our production environments for months now. You could always try running the main branch since these changes were merged and seeing if you hit any other unexpected issues. I don't know what triggers a new release or when the next one may be.

**Comment by BloodyIron** [comment]
> > So what's going on here with PHP8.x and OWA? 8 months since the last commit and radio silence for this and seemingly plenty other topics.
> > This tool _NEEDS_ to have PHP version support significantly increased as the currently max version of PHP it can work with has been EOL for a long time. This is causing lots of problems and it would benefit many to know what's going on, including threads like #893 and more.
> 
> We've been running with PHP8 in our production environments for months now. You could always try running the main branch since these changes were merged and seeing if you hit any other unexpected issues. I don't know what triggers a new release or when the next one may be.

I really would prefer to hold off until a new release happens. I don't know if there's added QA that happens in that workflow or other things I might care about.

**Comment by BloodyIron** [comment]
> > So what's going on here with PHP8.x and OWA? 8 months since the last commit and radio silence for this and seemingly plenty other topics.
> > This tool _NEEDS_ to have PHP version support significantly increased as the currently max version of PHP it can work with has been EOL for a long time. This is causing lots of problems and it would benefit many to know what's going on, including threads like #893 and more.
> 
> We've been running with PHP8 in our production environments for months now. You could always try running the main branch since these changes were merged and seeing if you hit any other unexpected issues. I don't know what triggers a new release or when the next one may be.

Which version of PHP8? v8.1 and v8.2 are now security-only and not far from full EOL.

**Comment by criterion9** [comment]
> > > So what's going on here with PHP8.x and OWA? 8 months since the last commit and radio silence for this and seemingly plenty other topics.
> > > This tool _NEEDS_ to have PHP version support significantly increased as the currently max version of PHP it can work with has been EOL for a long time. This is causing lots of problems and it would benefit many to know what's going on, including threads like #893 and more.
> > 
> > 
> > We've been running with PHP8 in our production environments for months now. You could always try running the main branch since these changes were merged and seeing if you hit any other unexpected issues. I don't know what triggers a new release or when the next one may be.
> 
> Which version of PHP8? v8.1 and v8.2 are now security-only and not far from full EOL.

We have 8.2 currently for our analytics environments but are planning moving to 8.3 shortly.

**Pull request merged**
