### PR TITLE
Feature: CLI Command to re-crawl Referring URLs

### PR DESCRIPTION
**Pull request by Maaiins**
Ref #496 

The part to re crawl `owa_document` is missing at the moment. I didn´t found the right lines in the code

### CODE REVIEW

**Comment by Maaiins** [comment]
Commit looks correct now

**Comment by znrR** [comment]
:-) i want to try it out, how do i do that - whats the command i need to perform?

**Comment by Maaiins** [comment]
To update all:
php cli.php cmd=update-referral

To update a specific id:
php cli.php cmd=update-referral ref=<owa_referer::id>

**Comment by znrR** [comment]
cool, it did work! I received an error in the console though: "Cannot load Zend OPcache - it was already loaded" not critical i guess

it also did not update all of the titles, for facebook it even included their html in OWA, see screenshot.. its not critical to me, but maybe you want to check whats going wrong there... 
Screenshot 2020-03-30 at 15 18 01

**Comment by znrR** [comment]
oh, and i just saw that the titles in the right hand column on the OWA dashbaord also get not updated... on their detail pages these titles are updated though.. maybe the titles for that top referrers get stored in a separated DB table?
Screenshot 2020-03-30 at 15 25 03

**Comment by Maaiins** [comment]
Well I just copied the crawling logic. So this bug or whatever came from earlier versions...

I would say open a separate Issue for this.

**Comment by znrR** [comment]
oki will do!

**Comment by Maaiins** [comment]
> oh, and i just saw that the titles in the right hand column on the OWA dashbaord also get not updated... on their detail pages these titles are updated though.. maybe the titles for that top referrers get stored in a separated DB table?
> Screenshot 2020-03-30 at 15 25 03

Try to flush your cache in the Administration panel. Please let me know if this works. I will add an automatic cache flush to the cli command.

**Comment by znrR** [comment]
hmm nope flush did not fix those!

**Comment by Maaiins** [comment]
Ah damn you said title is not updated properly. So this could be caused by this.

Can you confirm this?

Try to display Referral Web Site
image

**Comment by znrR** [comment]
oh lord, just visited again an now they get displayed... flushing cache works but needs a couple of minutes to take effect, it seams... referral webiste as secondary dimension displays URL, which works fine! Thanks, I think aside of the weird facebook html everything works!

**Comment by padams** [comment]
Strange. `$r->update();` should clear the entity object from the cache...

**Comment by znrR** [comment]
ok i can try that! but i ran into another bigger prob :-/ i downloaded the whole latest master and put that on the server (just kept owa-config and maxmind) and now tracking is borgged :-/

**Comment by Maaiins** [comment]
Which tacking are you using? JS or PHP?

**Comment by znrR** [comment]
wordpress - JS

**Comment by Maaiins** [comment]
@padams I can not debug wordpress but maybe some issue with this https://github.com/Open-Web-Analytics/Open-Web-Analytics/pull/498#discussion_r399971295

**Comment by Maaiins** [comment]
@znrR are there any javascript console errors?

**Comment by padams** [comment]
@znrR did you run `composer install`?

**Comment by znrR** [comment]
nope! no composer install! (also no errors in j-console or owa errors.txt

**Comment by padams** [comment]
You need to run `composer install` if you check code out of master. see: https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installing-from-Github

**Comment by znrR** [comment]
okay reading through how to install composer.. i thought i would only need that if i want to install "directly from git"... sounds not to complicated, let me see if i get that done. I guess after i installed composer, i will run a fresh update of owa directly from git? maybe i need further support on this!

**Comment by padams** [comment]
Always best to:

`git pull`
`composer install`

Specific releases will always have a downloadable tarball that contains all of the composer dependancies in it if you prefer that. However, that's not available for development code in master.

**Comment by znrR** [comment]
oh no! in order to run composer i would need to upgrade the dreamhost hostinig plan :-/ doubling costs actually.. damn!

**Comment by padams** [comment]
You could download the 1.6.6 release and copy its `vendor` directory over to where you installed the code from master. The Vendor directory is what Composer installs.

**Comment by znrR** [comment]
HURRAY!!! that brought back tracking (although there was one symblink in "vendor" that could not be copied..) oh my goodness, i promise to only install real releases from now on and never touch development code from master again!

**Comment by znrR** [comment]
thanks peter and nicolai for all that work you do and the endless support you give! will talk to my partner in crime about donating!

**Comment by Maaiins** [comment]
> Strange. `$r->update();` should clear the entity object from the cache...

Could also be a browser caching issue

**Comment by Maaiins** [comment]
> thanks peter and nicolai for all that work you do and the endless support you give! will talk to my partner in crime about donating!

Well i´m just another user of this project. But instead of donating I decided to support peter with my programming experience ;-)

**Comment by padams** [comment]
@Maaiins so appreciated and way better than any donation!!

**Pull request merged**
